name: Check Files on Pull Request

on:
  pull_request_target:  
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read  

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check .gitignore and added files
        id: check_gitignore
        run: |
          # Fetch the latest changes
          git fetch origin ${{ github.event.pull_request.base.ref }}

          # Check if .gitignore was added or modified in the pull request
          modified_gitignore=$(git diff --name-status origin/${{ github.event.pull_request.base.ref }}..HEAD | grep ".gitignore")

          # Check the content of the new or modified .gitignore
          new_gitignore=$(git show HEAD:.gitignore)

          if echo "$new_gitignore" | grep -q "enemies_shooting.py"; then
            echo "✅ enemies_shooting.py found in the added .gitignore!"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ enemies_shooting.py not found in the added .gitignore."
            echo "status=failure" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Comment on Pull Request
        if: steps.check_gitignore.outputs.status == 'success'  
        uses: mshick/add-pr-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  
        with:
          message: |
            ## 🎊 Congratulations, Hero! 🎊
            
            Batman reaches the remote from the **🟢 *courier room of the lounge* 🟢**! 🏢✈️

            Thank you for your heroic contribution! Keep up the great work! 🚀
