name: Check Files on Pull Request

on:
  pull_request_target:  
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read  

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check .gitignore and added files
        id: check_gitignore
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          added_files=$(git diff --name-status origin/${{ github.event.pull_request.base.ref }}..HEAD | grep '^A' | awk '{print $2}')

          if echo "$added_files" | grep -q "enemies_shooting.py"; then
            echo "❌ enemies_shooting.py found in added files."
            echo "status=failure" >> $GITHUB_ENV
            exit 1
          else
            echo "✅ enemies_shooting.py not found in added files!"
            echo "status=success" >> $GITHUB_ENV
          fi

      - name: Comment on Pull Request
        if: steps.check_gitignore.outputs.status == 'success'  
        uses: mshick/add-pr-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  
        with:
          message: |
            ## 🎊 Congratulations, Hero! 🎊
            
            Batman reaches the remote from the **🟢 *courier room of the lounge* 🟢**! 🏢✈️

            Thank you for your heroic contribution! Keep up the great work! 🚀
